Update types for Journal
BIBSYSDEV/NVA-scenarios pull request #156
Opened 2021-06-03 11:21 UTC by elkebab

Diverse endringer av typer for Journal ref nye skisser:

![bilde](https://user-images.githubusercontent.com/6313468/120636908-89116f80-c46e-11eb-8017-ffbef093533e.png)

2021-06-03 12:38 UTC, terjehell submitted a review, later dismissed

2021-06-03 18:37 UTC, brinxmat requested changes

2021-06-03 18:37 UTC, brinxmat commented on 26-register_registration/creator_navigates_to_resource_type_tab.feature
> +    And they see radio buttons for Present new original research
Presents

2021-06-04 09:57 UTC, brinxmat approved these changes

2021-06-04 10:41 UTC, terjehell approved these changes

2021-06-04 11:23 UTC, merged