Remove field for presents new original research
BIBSYSDEV/NVA-scenarios pull request #189
Opened 2021-09-03 08:57 UTC by elkebab

2021-09-03 09:10 UTC, terjehell requested changes

2021-09-03 09:10 UTC, terjehell commented on 26-register_registration/resource_types/creator_selects_resource_type_book.feature
>              | Peer reviewed         |
| Peer reviewed and presents new research |

2021-09-03 09:10 UTC, terjehell commented on 26-register_registration/resource_types/creator_selects_resource_type_chapter.feature
>              | Peer reviewed         |
| Peer reviewed and presents new research |

2021-09-03 10:07 UTC, terjehell approved these changes

2021-09-06 06:54 UTC, Eiriknil approved these changes

2021-09-06 10:28 UTC, merged