Editor decide publishing policy
BIBSYSDEV/NVA-scenarios pull request #195
Opened 2021-09-24 12:58 UTC by garshol

Created publishing_rights.feature
Have adjusted readme and owner_navigate_to_the_landing_page_for_theire_registration (sic!)  accordingly

2021-09-25 06:31 UTC, brinxmat requested changes

2021-09-25 06:31 UTC, brinxmat commented on 1226-editor/publishings_rights.feature
> +Feature: Editor decide who got publishing rights
decides who gets

2021-09-25 06:31 UTC, brinxmat commented on 1226-editor/publishings_rights.feature
> +		| Registrator got full publishing rights |
got -> has?

2021-09-25 06:31 UTC, brinxmat commented on 1226-editor/publishings_rights.feature
> +		| Registrator got full publishing rights |
got -> has?

2021-09-25 06:31 UTC, brinxmat commented on 1226-editor/publishings_rights.feature
> +	Scenario: Editor decide publishing rights
decide -> defines

2021-09-25 06:31 UTC, brinxmat commented on 1226-editor/readme
> +The Editor decide the Institutions publication policy and can choose one of the three options:
decide -> defines

2021-09-25 06:31 UTC, brinxmat commented on 1226-editor/readme
> +	Registrator got full publishing rights
got -> has

2021-09-25 06:31 UTC, brinxmat commented on 1226-editor/readme
> +See publishings_rights.feature for details.
publishing_rights.feature

2021-09-25 06:31 UTC, brinxmat commented on 1228-landing_page/owner_navigates_to_the_landing_page_for_their_registration.feature
> +        Given Institutions publications policy is "Only Curator can publish"
publications -> publication

2021-09-25 06:31 UTC, brinxmat commented on 1228-landing_page/owner_navigates_to_the_landing_page_for_their_registration.feature
> +        Then the Owner see a landingpage with an unpublished resource
the Owner sees the Landing page for the unpublished Resource?

2021-09-25 06:31 UTC, brinxmat commented on 1228-landing_page/owner_navigates_to_the_landing_page_for_their_registration.feature
> +        And an Approval Request is sent to his Curator
the user's institutional Curator?

2021-09-25 06:31 UTC, brinxmat commented on 1228-landing_page/owner_navigates_to_the_landing_page_for_their_registration.feature
> +        And the Owner is notified that a Approval Request is sent to his Curator and progress can be viwed in My Messages
an Approval…to the Curator

2021-09-25 06:31 UTC, brinxmat commented on 1228-landing_page/owner_navigates_to_the_landing_page_for_their_registration.feature
> +        Given Institutions publications policy is "Registrator can only publish metadata"
Institution(al)? publication, in all cases

2021-09-25 06:31 UTC, brinxmat commented on 1228-landing_page/owner_navigates_to_the_landing_page_for_their_registration.feature
> +        Given Institutions publications policy is "Registrator can only publish metadata"
I don't think you need "is"

2021-09-25 06:31 UTC, brinxmat commented on 1228-landing_page/owner_navigates_to_the_landing_page_for_their_registration.feature
> +        Then the Owner sees a landingpage with a Published Resource
See the previous comment about this

2021-09-25 06:31 UTC, brinxmat commented on 1228-landing_page/owner_navigates_to_the_landing_page_for_their_registration.feature
> +        And an Approval Request is sent to his Curator
the Curator

2021-09-25 06:31 UTC, brinxmat commented on 1228-landing_page/owner_navigates_to_the_landing_page_for_their_registration.feature
> +        And the Owner is notified that a Approval Request is sent to his Curator and progress can be viwed in My Messages
See previous comment about this line

2021-09-25 06:31 UTC, brinxmat commented on 1228-landing_page/owner_navigates_to_the_landing_page_for_their_registration.feature
> +        Given Institutions publications policy is "Registrator got full publishing rights"
Again

2021-09-25 06:31 UTC, brinxmat commented on 1228-landing_page/owner_navigates_to_the_landing_page_for_their_registration.feature
> +        And the Owner see a landingpage with a published resource
the Owner sees a landing page with a published Resource.

2021-09-25 06:31 UTC, brinxmat commented on 1228-landing_page/owner_navigates_to_the_landing_page_for_their_registration.feature
> +    Scenario: Owner wants to publish Resource, all restrictions
In this file, I feel we need to have consistent capitalisation of NVA concepts. Resource, maybe Published Resource and Landing page

2021-09-27 08:28 UTC, brinxmat requested changes

2021-09-27 08:28 UTC, brinxmat commented on 1226-editor/readme
> +	Registrator got full publishing rights
Still… :D

2021-09-27 13:06 UTC, brinxmat approved these changes

2021-09-27 13:17 UTC, terjehell approved these changes

2021-09-27 14:33 UTC, merged