Update my_worklist_ownership.feature
BIBSYSDEV/NVA-scenarios pull request #196
Opened 2021-09-27 11:54 UTC by garshol

Adding a new use case - take ownership of resource

2021-09-28 15:00 UTC, brinxmat requested changes

2021-09-28 15:00 UTC, brinxmat commented on 1228-landing_page/owner_navigates_to_the_landing_page_for_their_registration.feature
> +        Then the Owner must acknowledging that this is a final action
acknowledges that this

2021-09-29 08:10 UTC, garshol commented on 1223-curator_worklist/my_worklist_ownership.feature
> +		Editor seizes ownership of a Resource
Eg ønsker å skille mellom det editor gjer og det brukar gjer - når dei blir eigar.
Ein brukar krever å få ein ressurs overlevert av Kurator, mens editor berre tar ein ressurs - det er ikkje det samme.

Eg bytter derfor ut "seizes" med "takes" - og beheld "claims" som det står i dag.

2021-09-29 08:20 UTC, garshol commented on 1228-landing_page/owner_navigates_to_the_landing_page_for_their_registration.feature
> +        Then the Owner sees a option to transfers his Ownership of current Resource
usikker...

2021-09-29 09:03 UTC, brinxmat approved these changes

2021-09-30 10:13 UTC, terjehell approved these changes

2021-09-30 11:52 UTC, merged