Revision: My profile page
BIBSYSDEV/NVA-scenarios pull request #237
Opened 2022-05-18 07:52 UTC by Eiriknil

2022-05-19 07:37 UTC, terjehell approved these changes

2022-05-19 08:53 UTC, elkebab commented on 1217-my_profile_page/1724-non-customer_views_my_profile.feature
> +        And they see their Institutions name under Affiliations
```suggestion
        And they see their Institutions names under Affiliations
```

2022-05-19 13:55 UTC, terjehell requested changes

2022-06-09 06:56 UTC, Eiriknil commented on 1217-my_profile_page/1724-non-customer_views_my_profile.feature
> +        And they see their Institutions names under Affiliations
```suggestion
        And they see their Institutions names under Affiliations
        And they see their Feide Host ID
```

2022-06-10 14:43 UTC, elkebab approved these changes

2022-06-14 06:32 UTC, terjehell approved these changes

2022-06-20 05:48 UTC, merged