Revision to My institution
BIBSYSDEV/NVA-scenarios pull request #239
Opened 2022-05-19 08:14 UTC by Eiriknil

2022-05-19 08:54 UTC, terjehell approved these changes

2022-05-19 08:59 UTC, elkebab commented on 1225-my_institution/institution_administrator_edits_my_institution.feature
> +        And they click the menu item My institution
```suggestion
        And they click the menu item My Institution
```

2022-05-19 08:59 UTC, elkebab commented on 1225-my_institution/institution_administrator_edits_my_institution.feature
> +        And they click the menu item My institution
```suggestion
        When they click the menu item Basic Data
        And they click the menu item My Institution
```

2022-05-19 13:51 UTC, terjehell approved these changes

2022-05-20 11:28 UTC, terjehell approved these changes

2022-05-23 06:32 UTC, elkebab commented on 1225-my_institution/institution_administrator_edits_my_institution.feature
> +        And they click the menu item My Institution
Burde kanskje forenkle med å gjøre samme her som på den under?
```suggestion
        When they open My Institution
```

2022-06-10 11:04 UTC, elkebab approved these changes

2022-06-20 10:50 UTC, terjehell commented on 1225-my_institution/institution_administrator_edits_my_institution.feature
>      @361
Dette sceniariot kan slettes.

2022-06-22 07:51 UTC, elkebab requested changes
Denne PRen kan lukkes. Erstattes av https://github.com/BIBSYSDEV/NVA-scenarios/pull/247

2022-06-22 07:59 UTC, closed without merging