Adding @test to scenarios
BIBSYSDEV/NVA-scenarios pull request #259
Opened 2022-09-12 11:31 UTC by Eiriknil

2022-09-13 11:18 UTC, brinxmat requested changes

2022-09-13 11:18 UTC, brinxmat commented on 26-register_registration/resource_types/research_data/dmp.feature
> +	Scenario: User removes an related-references to resource
a related…

2022-09-14 05:50 UTC, brinxmat approved these changes

2022-09-14 09:55 UTC, elkebab approved these changes

2022-09-14 10:09 UTC, merged