Project scenarios revision
BIBSYSDEV/NVA-scenarios pull request #268
Opened 2022-11-17 07:12 UTC by Eiriknil

2022-11-24 11:45 UTC, elkebab commented on 1208-projects/my_projects.feature
> +            | Prosjekt category        |
```suggestion
            | Project category        |
```

2022-11-29 13:21 UTC, garshol submitted a review, later dismissed
juster linje 38 og tilsvarande i 59

2022-11-29 13:21 UTC, garshol commented on 1208-projects/my_projects.feature
> +        And the User can select a list of Concluded Projects
ladd also options to only view active/ongoing projects and draft projects

2022-11-29 13:21 UTC, garshol commented on 1208-projects/my_projects.feature
> +        And the User can navigate through the list of Concluded Projects
remove concluded

2022-12-06 09:37 UTC, garshol submitted a review, later dismissed

2022-12-06 10:00 UTC, Eiriknil commented on 1208-projects/project_wizard.feature
> +    #         | Published | Update published project |
```suggestion
```

2022-12-06 10:01 UTC, Eiriknil commented on 1208-projects/project_wizard.feature
> +        #     And the User is the Project Owner
```suggestion
```

2022-12-06 10:02 UTC, elkebab commented on 1208-projects/project_wizard.feature
> +    Scenario: The User opesn the Project Wizard on the last page
```suggestion
    Scenario: The User openn the Project Wizard on the last page
```

2022-12-06 10:02 UTC, garshol approved these changes

2022-12-06 10:04 UTC, elkebab commented on 1208-projects/project_wizard.feature
> +            | Project type         |
Finner ikke dette feltet i skissene
```suggestion
```
![bilde](https://user-images.githubusercontent.com/6313468/205880944-77fbcafa-4589-4e9d-9b68-baca6350f2c0.png)

2022-12-06 10:08 UTC, elkebab commented on 1208-projects/my_projects.feature
> +            | Project category         |
Skisser viser ingen prosjektkategori(?) hvis det er samme som "Prosjekttype" kan vi fjerne "Type" her
```suggestion
            | Type                     |
```
![bilde](https://user-images.githubusercontent.com/6313468/205881749-2f57a854-3d6c-454e-8d6d-886786ba2315.png)

2022-12-06 10:28 UTC, garshol requested changes

2022-12-06 10:28 UTC, garshol commented on 1208-projects/project_wizard.feature
> +            | Project type         |
Feltet ligger på toppen, i samme skjermbilde:
<img width="588" alt="image" src="https://user-images.githubusercontent.com/11860616/205885531-65a09bcc-0c7d-437e-8272-c8b2f1ba017f.png">
(Skissene viser slik dette er implementert i dag - i Cristin. Ny arbeidsgruppe, som er under etablering, har alt signalisert at dette må endres. Så ta raskeste vei til mål, med dette feltet - det vil bli justert når arbeidsgruppa blir etablert og eg får kontroll på kva som er ønsket kategorisering av prosjekt)

2022-12-06 10:28 UTC, garshol commented on 1208-projects/my_projects.feature
> +            | Project category         |
Slett linje 48. Her vil det komme endringer (seinare).

2022-12-06 10:45 UTC, garshol approved these changes

2022-12-06 11:25 UTC, elkebab approved these changes

2022-12-07 08:57 UTC, merged