User changes their institution on my profile
BIBSYSDEV/NVA-scenarios pull request #76
Opened 2020-10-21 06:31 UTC by sarahse

Det er et scenario her som har feil nummer. @Eiriknil - vet du hvilket nummer det skal være på `User sees a Subunit from My Profile`?

2020-10-22 08:48 UTC, sarahse commented on 1217-my_profile_page/40X-user_sees_a_subunit_from_my_profile.feature
> +    @
@Eiriknil : vet du hvilket nummer det egentlig skal være her? Det er ikke 406 hvertfall...

2020-10-22 10:58 UTC, Eiriknil commented on 1217-my_profile_page/40X-user_sees_a_subunit_from_my_profile.feature
> +    @
Skal prøve å finne det i jira

2020-10-22 11:07 UTC, Eiriknil commented on 1217-my_profile_page/40X-user_sees_a_subunit_from_my_profile.feature
> +    @
Finner ikke User sees a Subunit from My Profile i Jira. Kun User selects a Subunit from My Profile.

2020-10-22 11:08 UTC, Eiriknil commented on 1217-my_profile_page/40X-user_sees_a_subunit_from_my_profile.feature
> +    @
Foreslår å gi den nummeret 405 siden det ikke er i bruk.

2020-10-22 12:23 UTC, sarahse commented on 1217-my_profile_page/40X-user_sees_a_subunit_from_my_profile.feature
> +    @
ok, da gjør jeg det 👍

2020-10-23 06:19 UTC, Eiriknil approved these changes

2020-10-27 08:02 UTC, terjehell requested changes

2020-10-27 13:05 UTC, terjehell approved these changes

2020-10-28 13:29 UTC, elkebab commented on 1217-my_profile_page/406-user_changes_their_institution_on_my_profile.feature
> +        When they click Change Institution
Skal dette være et nytt valg i tillegg til "Legg til institusjon" og "Fjern" som vi har nå, eller skal dette erstatte "Fjern"? @terjehell @garshol

2020-10-28 13:38 UTC, sarahse commented on 1217-my_profile_page/406-user_changes_their_institution_on_my_profile.feature
> +        When they click Change Institution
Tror det skal være i tillegg til. Må tegnes på en god måte da 🤔

2020-10-28 14:51 UTC, elkebab commented on 1217-my_profile_page/406-user_changes_their_institution_on_my_profile.feature
> +        When they click Change Institution
ja, redd det kan bli utrivelig å implementere også (sånn som InstitutionSelector osv ser ut nå) :/

2020-10-28 14:51 UTC, elkebab approved these changes

2020-10-28 15:07 UTC, sarahse commented on 1217-my_profile_page/406-user_changes_their_institution_on_my_profile.feature
> +        When they click Change Institution
jepp, det blir ikke lett 🙂 🙂 🙂

2020-10-29 11:28 UTC, Eiriknil approved these changes

2020-10-29 12:28 UTC, merged