NP-357 Add new tabs to worklist
BIBSYSDEV/NVA-scenarios pull request #81
Opened 2020-10-30 08:19 UTC by elkebab

Om vi gjør det slik må NP-1352 i Jira slettes etterpå

2020-10-30 08:40 UTC, sarahse commented on 1223-curator_worklist/357-curator_opens_my_worklist.feature
> +        And the see that each Worklist Item has an Expand button
Det er en ganske stor feature dette da. Litt skeptisk til å ha så mange scenario i en feature, men hvis vi tenker på en feature i Jira som et scenario her, så er det vel greit

2020-10-30 08:40 UTC, sarahse approved these changes

2020-10-30 10:12 UTC, terjehell requested changes

2020-10-30 10:12 UTC, terjehell commented on 1223-curator_worklist/357-curator_opens_my_worklist.feature
> +            | Status    |
Request Status

2020-10-30 10:12 UTC, terjehell commented on 1223-curator_worklist/357-curator_opens_my_worklist.feature
> +            | Message   |
Remove Message

2020-10-30 10:12 UTC, terjehell commented on 1223-curator_worklist/357-curator_opens_my_worklist.feature
> +            | Submitter |
Submitter Name

2020-10-30 10:12 UTC, terjehell commented on 1223-curator_worklist/357-curator_opens_my_worklist.feature
> +            | Title     |
Publication Title

2020-10-30 10:12 UTC, terjehell commented on 1223-curator_worklist/357-curator_opens_my_worklist.feature
> +            | Submitter         |
Submitter Name

2020-10-30 10:12 UTC, terjehell commented on 1223-curator_worklist/357-curator_opens_my_worklist.feature
> +            | DOI request status |
Request Status

2020-10-30 10:12 UTC, terjehell commented on 1223-curator_worklist/357-curator_opens_my_worklist.feature
> +            | Submitter          |
Submitter Name

2020-10-30 11:27 UTC, terjehell approved these changes

2020-10-30 11:33 UTC, sarahse commented on 1223-curator_worklist/357-curator_opens_my_worklist.feature
> +            | Publication title |
```suggestion
            | Registration title |
```

2020-10-30 11:35 UTC, sarahse commented on 1223-curator_worklist/357-curator_opens_my_worklist.feature
> +        Then they see a list of Worklist items with fields:
```suggestion
        Then they see a list of Worklist Items with fields:
```

2020-10-30 11:35 UTC, sarahse commented on 1223-curator_worklist/357-curator_opens_my_worklist.feature
> +        And they see each Worklist Item has an Expand button
```suggestion
        And they see that each Worklist Item has an Expand button
```

2020-10-30 12:09 UTC, sarahse commented on 1223-curator_worklist/357-curator_opens_my_worklist.feature
> +            | Registration title |
weird formattering her

2020-10-30 12:35 UTC, sarahse approved these changes

2020-11-02 07:30 UTC, Eiriknil approved these changes

2020-11-03 08:09 UTC, merged