Np 1837 add myself as author
BIBSYSDEV/NVA-scenarios pull request #84
Opened 2020-11-18 12:31 UTC by elkebab

2020-11-18 12:32 UTC, terjehell approved these changes

2020-11-18 12:41 UTC, brinxmat requested changes

2020-11-18 12:41 UTC, brinxmat commented on 26-register_publication/creator-navigates-to-contributor-tab.feature
> +    Given Creator begins registering a Registration in the Wizard
s/Registration/Publication/?

2020-11-18 12:41 UTC, brinxmat commented on 26-register_publication/creator-navigates-to-contributor-tab.feature
> +  Scenario: Creator adds themselves to list of Authors
Haha, my dialect has "themself", but it isn't a word in English

2020-11-18 12:41 UTC, brinxmat commented on 26-register_publication/creator-navigates-to-contributor-tab.feature
> +    Given Creator begins registering a Registration in the Wizard
s/Registration/Publication/

2020-11-18 12:45 UTC, elkebab commented on 26-register_publication/creator-navigates-to-contributor-tab.feature
> +    Given Creator begins registering a Registration in the Wizard
Registration er riktig

2020-11-19 09:43 UTC, Eiriknil approved these changes

2020-12-10 14:15 UTC, terjehell submitted a review, later dismissed

2020-12-11 10:30 UTC, elkebab commented on 26-register_publication/creator-navigates-to-contributor-tab.feature
> +    Given Creator begins registering a Registration in the Wizard
I forbindelse med brukertestene ble det bestemt at det vi lager skal kalles "Registration" mot brukerene. Om man starter registrering med DOI vil denne DOIen peke mot en "Publication", men i NVA registrerer brukeren en "Registration". Det blir i hvert fall terminologien PO har bestemt skal brukes mot brukerene, derfor syns jeg det blir mest logisk å bruke her også

2021-01-18 07:27 UTC, brinxmat submitted a review, later dismissed

2021-01-21 08:21 UTC, Eiriknil submitted a review, later dismissed

2021-01-21 10:36 UTC, brinxmat approved these changes

2021-01-21 10:41 UTC, sarahse commented on 26-register_publication/creator-navigates-to-contributor-tab.feature
> +    Then their Author identity are appended to list of Authors
Identity er entall? 

```suggestion
    Then their Author identity is appended to list of Authors
```

2021-01-27 07:13 UTC, sarahse approved these changes

2021-02-02 12:50 UTC, Eiriknil approved these changes

2021-02-03 07:34 UTC, merged